# Generated by Django 5.0.6 on 2024-07-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='idx',
            field=models.IntegerField(blank=True, help_text='Position IDs for ML', null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='rating_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
