# Generated by Django 5.0.6 on 2024-07-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='description',
            new_name='overview',
        ),
    ]
